# Generated by Django 4.1.4 on 2023-01-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_date',
        ),
    ]
